const productos = [
  {
    id: 1,
    stock: 25,
    categoria: "Componentes",
    titulo: "Pantalla",
    descripcion: "Pantalla Samsung 4k....",
    precio: 200,
    img: "/images/pantalla.png",
  },
  {
    id: 2,
    stock: 20,
    categoria: "Componentes",
    titulo: "Teclado",
    descripcion: "Teclado gamer con 8 luces led.....",
    precio: 25,
    img: "/images/teclado.png",
  },
  {
    id: 3,
    stock: 30,
    categoria: "Componentes",
    titulo: "Mouse",
    descripcion: "Mouse gamer inalámbrico con luces led.....",
    precio: 20,
    img: "/images/mouse.png",
  },
  {
    id: 4,
    stock: 60,
    categoria: "Componentes",
    titulo: "Parlante",
    descripcion: "Parlante rojo.....",
    precio: 10,
    img: "/images/corneta.png",
  },
  {
    id: 5,
    stock: 6,
    categoria: "Pc",
    titulo: "Pc Gamer H105",
    descripcion: "Pc gamer 16gb ram.....",
    precio: 1000,
    img: "/images/pc1.png",
  },
  {
    id: 6,
    stock: 60,
    categoria: "Componentes",
    titulo: "Micrófono",
    descripcion: "Micrófono.....",
    precio: 15,
    img: "/images/microfono.png",
  },
  {
    id: 7,
    stock: 10,
    categoria: "Laptop",
    titulo: "Laptop MH-1204",
    descripcion: "Laptop 4gb ram .......",
    precio: 600,
    img: "/images/laptop1.png",
  },
  {
    id: 8,
    stock: 16,
    categoria: "Pc",
    titulo: "Pc MZ-204",
    descripcion: "Pc 6gb ram con teclado incluido.......",
    precio: 850,
    img: "/images/pc2.png",
  },
];
export default productos;
